In [1]:
# import modules for math and distributions
from math import exp
import numpy as np
from scipy.stats import gamma, norm, uniform, bernoulli
import pandas as pd
import statsmodels.api as sm
import rpy2
import patsy
import pdb

In [2]:
# required to be able to work with rpy2
%load_ext rpy2.ipython

In [3]:
# define inverse logit function
def expit(x): return(exp(x)/(1 + exp(x)))

In [4]:
# Initial set up following to HD2012
T = 40 # time periods
k = 5 # check-up times
theta = [-0.405, 0.0205, -0.00405]
gam = [-3, 0.05, -1.5, 0.1]

In [5]:
# make a function that does all of the above for an individual
def sim(T, k, gam, theta, patid=0):

    # define lists for holding A, L, U and Y
    A = -1*np.ones(T + 2) # A[-1] (last value) holds A in t = -1
    L = np.zeros(T+1)
    U = np.zeros(T+1)
    Y = -1*np.ones(T + 2)
    eps = np.zeros(T+1)
    lam = np.zeros(T+1) # prob of failure at each time period
    delta = np.zeros(T+1)

    # set the first value of U, U[0], to a 
    # randomly generated value from a uniform
    # distribution a measure of general health
    U[0] = uniform.rvs()
    eps[0] = norm.rvs(0, 20)
    L[0] = gamma.ppf(U[0], 3, scale=154) + eps[0]
    # L[0] = max(0, gamma.ppf(U[0], 3, scale=154) + eps[0])

    # set A[-1] to 0: held in last value of A
    A[-1] = 0
    Y[0] = 0
    
    # set A[0]
    A[0] = bernoulli.rvs(expit(theta[0] + theta[2] * (L[0] - 500)), size=1)
    
    if A[0] == 1:
        Ts = 0 
    else:
        Ts = -1
    
    lam[0] = expit(gam[0] + gam[2] * A[0])
    
    if lam[0] >= U[0]:
        Y[1] = 1
    else:
        Y[1] = 0
    # loop through each time period - stop when patient is dead or t = T + 1
    for t in range(1, T+1):
        if Y[t] == 0:
            delta[t] = norm.rvs(0, 0.05)
            U[t] = min(1, max(0, U[t-1] + delta[t]))
            if t % k != 0:
                L[t] = L[t-1]
                A[t] = A[t-1]
            else:
                eps[t] = norm.rvs(100 * (U[t] - 2), 50)
                L[t] = max(0, L[t-1] + 150 * A[t-k] * (1-A[t-k-1]) + eps[t])
                if A[t-1] == 0:
                    A[t] = bernoulli.rvs(expit(theta[0] + theta[1] * t + theta[2] * (L[t] - 500)), size=1)
                else:
                    A[t] = 1
                if A[t] == 1 and A[t-k] == 0: 
                    Ts = t
            ########################################
            # This is a check for debugging purposes
            # Comment it before the next push
            if Ts == -1:
                if A[t]:
                    print('There is an error...')
            ########################################
            lam[t] = expit(gam[0] + gam[1] * ((1 - A[t]) * t + A[t] * Ts) + gam[2] * A[t] + gam[3] * A[t] *(t - Ts))
            if (1 - np.prod(1 - lam)) >= U[0]:
                Y[t + 1] = 1
            else:
                Y[t+1] = 0
        else:
            break
    
    #we only need the data before death, so whatever value t is before the end of the
    #above loop - change this to numpy array and transpose.
    Y = np.ndarray.tolist(Y[1:(t+1)])
    U = np.ndarray.tolist(U[0:t])
    L = np.ndarray.tolist(L[0:t])
    A = np.ndarray.tolist(A[0:t])
    Ts = [Ts]*t

    df = np.vstack((Y, L, U, A, Ts))
    df = pd.DataFrame(df.T, columns=['Y', 'L', 'U', 'A', 'Ts'])
    df['Y'] = df['Y'].astype(int)
    df['A'] = df['A'].astype(int)
    df['patid'] = patid
    df.index.name = 'visit'
    return df.reset_index()

In [6]:
# use sim function to make a pandas DF for n patients
def get_sim_data(T, k, gam, theta, n = 1000):

    # get data for each of 1000 patients
    frames = [sim(T, k, gam, theta, patid=i) for i in range(n)]
    df = pd.concat(frames)
    # make new variables for the logit regression
    # including an intercept
    df["d1"] = (1-df['A'])*df['visit'] + df['A']*df['Ts']
    df["d3"] = df['A']*(df['visit']-df['Ts'])
    # df["time_Ts"] = df["visit"] - df["Ts"]
    df = df.set_index(['patid', 'visit'])
    df = df.sort_index()
    
    #create two new variables 
    df["L_100"] = df["L"]/100
    def func(x):
        x["Lav_100"] = x["L"].mean()/100
        return x

    df = df.groupby(level="patid").apply(func)
    
    # get the previous value of A, and set first value of A_1 per patient to zero.
    df['A_1'] = df.groupby(level="patid")['A'].shift(1)
    df['A_1'] = df['A_1'].fillna(0)

    return(df)

In [7]:
def get_weights(df):
    
    # only need data when A is not 1 yet
    df["As"] = df.groupby(level="patid")['A'].cumsum()
    df2 = df[df["As"] <= 1].copy(deep=True)

    # numerator
    f = "A ~ 1"
    y, X = patsy.dmatrices(f, df2.reset_index(), return_type = "dataframe")
    n_logit = sm.Logit(y, X, missing="raise")
    n_result = n_logit.fit(disp=0, maxiter=100)
    df2["pn"] = n_result.predict()
    
    # denominator
    f = "A ~ L"
    y, X = patsy.dmatrices(f, df2.reset_index(), return_type = "dataframe")
    d_logit = sm.Logit(y, X, missing="raise")
    d_result = d_logit.fit(disp=0, maxiter=100)
    df2["pd"] = d_result.predict()

    # if A == 0, change probabilities to 1 - prob
    df2['pn2'] = np.where(df2['A']==0, (1 - df2["pn"]), df2["pn"])
    df2['pd2'] = np.where(df2['A']==0, (1 - df2["pd"]), df2["pd"])

    # construct stabilized weights, don't forget to group by
    df2['cpn'] = df2.groupby(level=0)['pn2'].cumprod()
    df2['cpd'] = df2.groupby(level=0)['pd2'].cumprod()
    df2['sw'] = df2['cpn']/df2['cpd']

    #combine df and df2
    df["sw"] = np.nan
    df.loc[df2.index, "sw"] = df2["sw"]
    df["sw"] = df["sw"].fillna(method="pad")
    
    return(df)


In [8]:
df = get_sim_data(T, k, gam, theta, n = 1000)
df = get_weights(df)

In [9]:
tmp = df.reset_index()
tmp.head()

patid  visit  Y           L         U  A   Ts   d1   d3     L_100  \
0      0      0  0  352.653604  0.407933  0  5.0  0.0 -0.0  3.526536   
1      0      1  0  352.653604  0.434455  0  5.0  1.0 -0.0  3.526536   
2      0      2  0  352.653604  0.456517  0  5.0  2.0 -0.0  3.526536   
3      0      3  0  352.653604  0.400878  0  5.0  3.0 -0.0  3.526536   
4      0      4  0  352.653604  0.429041  0  5.0  4.0 -0.0  3.526536   

    Lav_100  A_1  As        sw  
0  1.794866  0.0   0  1.108602  
1  1.794866  0.0   0  1.228999  
2  1.794866  0.0   0  1.362470  
3  1.794866  0.0   0  1.510438  
4  1.794866  0.0   0  1.674474

In [10]:
%%R -i tmp -o co
library(ipw)
library(survey)
tmp$tstart <- tmp$visit - 1
co <- matrix(NA, nrow= 100, ncol = 4)
ipwsw <- ipwtm(exposure = A, family = "survival",
               numerator = ~ 1, denominator = ~ L,
               id = patid, timevar = visit, tstart = tstart,
               type = "first", data = tmp)
tmp$ipwsw <- ipwsw$ipw.weights
desipw <- svydesign(ids = ~ 1, data = tmp, weights = ~ ipwsw)
mdl <- svyglm(Y ~ d1 + A + d3, design = desipw, family = quasibinomial())
co <- coef(mdl)
print(summary(mdl))

In [11]:
import rpy2.robjects as robjects
robjects.r('''
       runreg <- function(tmp){
       library(ipw)
       library(survey)
       tmp$tstart <- tmp$visit - 1
       ipwsw <- ipwtm(exposure = A, family = "survival", # survival model for weights
       numerator = ~ 1, denominator = ~ L,
       id = patid, timevar = visit, tstart = tstart,
       type = "first", data = tmp)
       tmp$ipwsw <- ipwsw$ipw.weights
       #desipw <- svydesign(ids = ~ 1, data = tmp, weights = ~ ipwsw)
       #mdl <- svyglm(Y ~ d1 + A + d3, design = desipw, family = quasibinomial())
       mdl <- glm(Y ~ d1 + A + d3, data = tmp, weights=ipwsw, family=binomial)
       return(coef(mdl))
       }
''')

r_runreg = robjects.globalenv['runreg']
r_runreg(tmp)

B = 100
co = np.zeros((B, 4))
for i in range(B):
    df = get_sim_data(T, k, gam, theta, n = 1000)
    df = get_weights(df)
    tmp = df.reset_index()
    co[i] = r_runreg(tmp)
    

In [12]:
co

array([[-3.00690191,  0.05181877, -1.5727223 ,  0.11187539],
       [-3.0072806 ,  0.04734704, -1.69584054,  0.11520643],
       [-2.83214421,  0.02293514, -1.76089445,  0.12051945],
       [-3.01565053,  0.04504919, -1.46877739,  0.09843747],
       [-2.88602081,  0.03188477, -1.70285052,  0.12077763],
       [-2.75121475,  0.03294478, -1.65703568,  0.10200966],
       [-2.91968821,  0.04030484, -1.80755729,  0.12325892],
       [-2.79032903,  0.02599701, -1.65941725,  0.10472332],
       [-2.69104896,  0.01753536, -1.92260161,  0.1162585 ],
       [-2.79747971,  0.03554849, -1.67677932,  0.11197548],
       [-2.95219002,  0.04145597, -1.64673384,  0.12030918],
       [-2.92144198,  0.04962684, -1.9691075 ,  0.13280718],
       [-2.88612119,  0.03930819, -1.69489589,  0.11513958],
       [-2.91971183,  0.04309567, -1.50839309,  0.09901047],
       [-2.93375906,  0.04003876, -1.42987387,  0.09685883],
       [-3.01519651,  0.0594702 , -1.74926907,  0.12335843],
       [-3.06465383,  0.

In [13]:
print(co.mean(axis = 0))
print(co.std(axis = 0))

[-2.94866122  0.04184118 -1.6086875   0.11016183]
[ 0.08972626  0.00890674  0.12488007  0.00777433]


In [14]:
# # MC 
# B = 50 # replications
# MC1 = np.zeros((B, 4))
# # MC2 = np.zeros((B, 5))
# # MC3 = np.zeros((B, 5))
# # MC4 = np.zeros((B, 4))

# for i in range(B):
    
#     df = get_sim_data(T, k, gam, theta, n = 1000)
#     df = get_weights(df)
    
#     f = "Y ~ 1 + d1 + A + d3"
#     y, X = patsy.dmatrices(f, df.reset_index(), return_type = "dataframe")
#     mod = sm.Logit(y, X, missing="raise")
#     MC1[i] = mod.fit(disp=0).params.values

# #     f = "Y ~ 1 + d1 + A + d3 + L_100"
# #     y, X = patsy.dmatrices(f, df.reset_index(), return_type = "dataframe")
# #     mod = sm.Logit(y, X, missing="raise")
# #     MC2[i] = mod.fit().params.values

# #     f = "Y ~ 1 + d1 + A + d3 + Lav_100"
# #     y, X = patsy.dmatrices(f, df.reset_index(), return_type = "dataframe")
# #     mod = sm.Logit(y, X, missing="raise")
# #     MC3[i] = mod.fit().params.values

In [15]:
# print(MC1.mean(axis = 0))
# print(MC1.std(axis = 0))
# # print(MC2.mean(axis = 0))
# # print(MC2.std(axis = 0))
# # print(MC3.mean(axis = 0))
# # print(MC3.std(axis = 0))